# site settings
title: Forty
subtitle: by HTML5 UP
email: sahyagiri@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/sahyagiri/garbagein-garbageout/" # the subpath of your site, e.g. /blog
url: https://sahyagiri.github.io/garbagein-garbageout
author: Gireesan Namboothiri P. 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/sahyagiri
instagram_url: https://instagram.com/sahyagiri
linkedin_url: https://www.linkedin.com/in/sahyagiri
pinterest_url:
twitter_url: https://twitter.com/sahyagiri

# build settings
markdown: kramdown

sass:
  style: compressed
